ATL-4-BE: Add api endpoints for member profile view
NUS-Fintech-Society/SD_Atlas pull request #10
Opened 2022-10-16 18:45 UTC by charmainehly

2022-10-17 10:34 UTC, woowenjun99 commented
Hi @charmainehly Thanks for putting in the effort. It's a good attempt and the code is readable and well-written. The logic meets the requirement. 😅

2022-10-17 10:41 UTC, woowenjun99 requested changes
Database calls are generally correct.

2022-10-17 10:41 UTC, woowenjun99 commented on src/pages/api/member/[member].ts
> +export const getServerSideProps = async (context: { params: { studentId: string; }; }) => {
May I trouble you to shift this segment of the code to the TRPC? You may take reference from the /server/router/example.ts and merge it in to the index.ts. The same applies for the remaining 4 files

2022-10-18 13:56 UTC, xianlinc reviewed
Can I check how we are retrieving an existing member image from the DB? If we dont have that yet, it would be great if you could have your api return the image as well.

2022-10-19 10:44 UTC, woowenjun99 commented on src/server/router/member_profile.ts
> +        input: z
I think you can replace this with 
```
input: z.string()
```

without the object

2022-10-19 10:47 UTC, woowenjun99 commented on src/server/router/member_profile.ts
> +import {prisma} from "../db/client";
Can try running `yarn prettier --write .` to format the entire file because I noticed that there is an inconsistency in the bracketing and the spacing

2022-10-19 10:50 UTC, woowenjun99 commented on src/server/router/member_profile.ts
> +                return {
Maybe it might help to just 

```ts
return user
```

2022-10-19 10:52 UTC, woowenjun99 commented
Good job, keep up the efforts, just some minor changes and it should be ok to merge with the Evan's branch :)

2022-10-20 12:54 UTC, merged

2022-10-20 12:54 UTC, xianlinc commented
LGTM